[project]
name = "mediaconverter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hdr-conversion>=0.1.4",
    "colour-science>=0.4.6",
    "imagecodecs>=2025.11.11",
    "numpy>=2.3.1",
    "opencv-python>=4.11.0.86",
    "tqdm>=4.67.3",
    "scipy>=1.17.1",
    "matplotlib>=3.10.8",
]
